### ISSUE TITLE
Name conflict with other cloudflare operator and more

### ISSUE THREAD

**Issue by urbaman** [containeroo/cloudflare-operator#232]
Hi,

Is there any conflict with the other repo with the same name that manages cloudflared? Can I install both?

There is another similar project to this, kubeflare. Are the projects talking to each other?

Thank you very much.

**Comment by rxbn** [comment]
Hi @urbaman 

Thanks for reaching out to us.

In general, we recommend installing only one operator that manages your DNS records.

For example, if you have a DNS record declared in our cloudflare-operator, but not in the other, chances are that it will delete that record, since it doesn't know anything about it. Which means that you would have to duplicate the configuration for each operator.

kubeflare is not affiliated with us and it looks like it isn't being actively maintained.

Best,
-- Robin

**Comment by acuntex** [comment]
I think OP was talking about https://github.com/adyanth/cloudflare-operator
It is an operator that is responsible for creating CloudFlare tunnels and also creates DNS entries for these tunnels.
Unfortunately containeroo/cloudflare-operator would delete these records needed for the tunnels as far as I understood.

Would it be feasible if containeroo/cloudflare-operator had some mode that would not delete everything it didn't create or have under management at a point in time?
